version: '3.8'

services:
  # Base de datos de métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: newbiesoft_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitor/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Visualización de datos
  grafana:
    image: grafana/grafana:latest
    container_name: newbiesoft_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Contraseña inicial
    depends_on:
      - prometheus
