# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      # Checkout the code as the first step
      - checkout

      # Restore cached Maven dependencies
      - restore_cache:
          keys:
            - maven-deps-{{ checksum "pom.xml" }}
            - maven-deps-

      # Install dependencies (and run tests)
      - run:
          name: Install and test
          command: mvn clean install

      # Save Maven dependencies to cache
      - save_cache:
          paths:
            - ~/.m2
          key: maven-deps-{{ checksum "pom.xml" }}

workflows:
  build_and_test:
    jobs:
      - build
