global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'newbiesoft-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # Apunta a tu app Java corriendo en local